Mobile Navigation bar
DevsThatMatter/nksm pull request #41
Opened 2024-02-04 15:20 UTC by heydoyouknowme0

Things remain to be Implemented.

- [ ]  Final Ui and colors( essential to change icon background on dark more
- [ ]  content specific icons
- [ ] Consideration to hiding to top navigation component

Closes  #23

2024-02-06 09:37 UTC, geekysilento commented
![image](https://github.com/DevsThatMatter/nksm/assets/125768789/d3815b90-e1c5-4b15-8859-b2bcc7c2838e)
fix the weird lines appearing under the 'plus' button, other than that looks good.

2024-02-10 16:22 UTC, geekysilento requested changes
remember to add husky and finish up the pr

2024-02-10 16:47 UTC, heydoyouknowme0 commented on app/(root)/layout.tsx
> maybe put the rendering bottomNav logic in a separate file and reference it here, instead of pasting the code right in layout.tsx?
> 

Oh yaar thwada dimaag kharab hai

2024-02-20 14:41 UTC, geekysilento approved these changes
Looks good

2024-02-20 14:42 UTC, merged